ABUSEIPDB_API_KEY = "YOUR_API_KEY_HERE"
ABUSEIPDB_URL = "https://api.abuseipdb.com/api/v2/check"

BRUTE_FORCE_THRESHOLD_HIGH = 3
BRUTE_FORCE_THRESHOLD_CRITICAL = 5
SPIKE_WINDOW_SECONDS = 300
SPIKE_COUNT_THRESHOLD = 10

ABUSE_SCORE_MALICIOUS = 75
ABUSE_SCORE_SUSPICIOUS = 40

SEVERITY_LEVELS = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]

OUTPUT_ALERTS_PATH = "output/alerts.json"
OUTPUT_REPORT_PATH = "output/report.txt"
